name: Deploy to AWS

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Pull the Docker image
        run: sudo docker pull vietnhat0351/github-actions:latest
