name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: linux

    steps:
    - uses: actions/setup-java@v3
      name: Set up JDK 17
      with:
        distribution: 'corretto'
        java-version: '17'
    - name: Build with Maven
      run: |
        mvn clean
        mvn -B package --file pom.xml
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: sudo docker build -t vietnhat0351/github-actions .
    - name: Push to Dockerhub
      run: sudo docker push vietnhat0351/github-actions:latest
